# -*- coding: utf-8 -*-
"""apyorii.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plXimww85qhhxgBzP_9snbUlOBBziPtX
"""
import pandas as pd

#baca file excel dan mengambil 2 sheet di bulan oktober dan november
xls = pd.ExcelFile('Data_Transaksi_Oktober_November.xlsx')
df_okt = xls.parse('Oktober 2024')
df_nov = xls.parse('November 2024')

# 5. Gabungkan data & urutkan berdasarkan tanggal
df_all = pd.concat([df_okt, df_nov], ignore_index=True)
df_all = df_all.sort_values(by="Tanggal Transaksi").reset_index(drop=True)

#kelompokan data berdasarkan tanggal transaksi
df_grouped = df_all.groupby('Tanggal Transaksi')['Nama Barang'].apply(list).tolist()

#import tools dari mIxtend
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# 7. Encode transaksi ke format True/False
te = TransactionEncoder()
te_array = te.fit_transform(df_grouped)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

#import tools dari mIxtend
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_array = te.fit_transform(df_grouped)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

# Apriori: bisa ubah support sesuai kebutuhan, cari itemset yang sering muncul
frequent_itemsets = apriori(df_encoded, min_support=0.1, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

rules['rekomendasi_display'] = rules.apply(
    lambda row: f"Jika membeli {set(row['antecedents'])}, maka cenderung membeli {set(row['consequents'])}",
    axis=1
)

# Tampilkan aturan asosiasi
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='confidence', ascending=False))

#mengurutkan dari lift, support dan confidence tertinggi ke terendah
rules.sort_values(
    by=['confidence', 'support', 'lift'],
    ascending=[False, False, False]
)[['rekomendasi_display', 'support', 'confidence', 'lift']].head(10)